title: Mina Sami
role: Senior Product Manager | Ex-Microsoft | Ex-P&G
summary: A product builder with a diverse background who loves to get things done

email: sami.mg@outlook.com
github_username: sami-m-g
linkedin_username: mina-sami
