title: Mina Sami
summary: >
  A product builder with a diverse background who loves to get things done,
  creating meaningful impact for millions of humans.

email: sami.mg@outlook.com
github_username: sami-m-g
linkedin_username: mina-sami

google_custom_map_id: 1sSjcdmMBTIjVHe5l6EPxsZkPiPqEEfo
