title: Mina Sami
role: Product @ Procore | Ex-Microsoft | Ex-P&G
summary: >
  A product builder with a diverse background who loves to get things done,
  creating meaningful impact for hundreds of thousands of humans.

email: sami.mg@outlook.com
github_username: sami-m-g
linkedin_username: mina-sami
